#!/bin/bash
ROOT=$OPENSHIFT_DATA_DIR
SONAR_VERSION=5.1.2

cd $ROOT

wget -q -c http://dist.sonar.codehaus.org/sonarqube-$SONAR_VERSION.zip
unzip sonarqube-$SONAR_VERSION.zip
rm -Rf sonarqube sonarqube-$SONAR_VERSION.zip
mv sonarqube-$SONAR_VERSION sonarqube

cd sonarqube/conf

if [[ $OPENSHIFT_MYSQL_DB_URL ]]
then
  JDBC_USERNAME=$OPENSHIFT_MYSQL_DB_USERNAME
  JDBC_PASSWORD=$OPENSHIFT_MYSQL_DB_PASSWORD
  sed -i "s;^sonar.jdbc.url.*;sonar.jdbc.url=jdbc:mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true;" sonar.properties
fi

if [[ $OPENSHIFT_POSTGRESQL_DB_URL ]]
then
  JDBC_USERNAME=$OPENSHIFT_POSTGRESQL_DB_USERNAME
  JDBC_PASSWORD=$OPENSHIFT_POSTGRESQL_DB_PASSWORD
  sed -i "s;^sonar.jdbc.url.*;sonar.jdbc.url=$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT/$PGDATABASE;" sonar.properties
fi

sed -i "s/^#sonar.web.host.*$/sonar.web.host=$OPENSHIFT_DIY_IP/" sonar.properties
sed -i "s/^#sonar.web.port.*$/sonar.web.port=$OPENSHIFT_DIY_PORT/" sonar.properties

if [[ $OPENSHIFT_MYSQL_DB_URL || $OPENSHIFT_POSTGRESQL_DB_URL ]]
then
  sed -i "s/^sonar.jdbc.username.*$/sonar.jdbc.username=$JDBC_USERNAME/" sonar.properties
  sed -i "s/^sonar.jdbc.password.*$/sonar.jdbc.password=$JDBC_PASSWORD/" sonar.properties
fi

cd $OPENSHIFT_DATA_DIR
rm -rf logs
ln -s $OPENSHIFT_LOG_DIR logs

cd $OPENSHIFT_DATA_DIR/sonarqube
rm -rf logs
ln -s $OPENSHIFT_LOG_DIR logs

cd $OPENSHIFT_DATA_DIR/tomcat
rm -rf logs
ln -s $OPENSHIFT_LOG_DIR logs

rm ${OPENSHIFT_DATA_DIR}sonarqube/bin/linux-x86-64/lib/libwrapper-*
rm ${OPENSHIFT_DATA_DIR}sonarqube/lib/wrapper-*
curl -o ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz http://wrapper.tanukisoftware.com/download/3.5.9/wrapper-delta-pack-3.5.9.tar.gz
tar -zxvf ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz -C ${OPENSHIFT_DATA_DIR}
rm ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/lib/wrapper.jar ${OPENSHIFT_DATA_DIR}sonarqube/lib/wrapper.jar
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/bin/wrapper-linux-x86-64 ${OPENSHIFT_DATA_DIR}sonarqube/bin/linux-x86-64/wrapper
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/lib/libwrapper-linux-x86-64.so ${OPENSHIFT_DATA_DIR}sonarqube/bin/linux-x86-64/lib/libwrapper.so

echo -e "\nwrapper.backend.type=PIPE" >> ${OPENSHIFT_DATA_DIR}sonarqube/conf/wrapper.conf



